# Generated by Django 4.1.1 on 2022-09-25 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odds', '0002_alter_city_options_alter_match_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='odds',
            name='us_away_odds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='odds',
            name='us_home_odds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='odds',
            name='away_odds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='odds',
            name='home_odds',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
