# Generated by Django 4.1.1 on 2022-09-25 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odds', '0003_odds_us_away_odds_odds_us_home_odds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odds',
            name='us_away_odds',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='odds',
            name='us_home_odds',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
