# Generated by Django 4.1.1 on 2022-09-25 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        ('odds', '0004_alter_odds_us_away_odds_alter_odds_us_home_odds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='away_team',
        ),
        migrations.RemoveField(
            model_name='match',
            name='home_team',
        ),
        migrations.RemoveField(
            model_name='match',
            name='league',
        ),
        migrations.RemoveField(
            model_name='team',
            name='city',
        ),
        migrations.RemoveField(
            model_name='team',
            name='league',
        ),
        migrations.AlterField(
            model_name='odds',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odds_set', to='games.match'),
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='League',
        ),
        migrations.DeleteModel(
            name='Match',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
