# Generated by Django 4.1.1 on 2022-09-28 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odds', '0006_remove_bookie_base_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='odds',
            name='external_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='odds',
            name='refreshed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='odds',
            name='url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
