# Generated by Django 4.1.1 on 2022-09-29 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('odds', '0007_odds_external_id_odds_refreshed_at_odds_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArbitragePossibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('away_stake', models.FloatField()),
                ('home_stake', models.FloatField()),
                ('margin', models.FloatField()),
                ('away_odds', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arbitrage_away_set', to='odds.odds')),
                ('home_odds', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arbitrage_home_set', to='odds.odds')),
            ],
        ),
    ]
