# Generated by Django 4.1.1 on 2022-09-28 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='sport',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
